"""Integration test for the release-artifact orchestrator (no mocks; real subprocess).

``scripts/generate_release_artifacts.py`` is named as a first-class regeneration
entry point in this exemplar's AGENTS.md ("release artifacts under
``output/reports/`` are regenerated by ... ``scripts/generate_release_artifacts.py``
and must not be hand-edited") and in README.md, and its declared outputs are
listed as ``artifact_expectations`` in ``domain_profile.yaml``. The sibling
script ``generate_figures.py`` has its own integration test
(``test_generate_figures_script.py``); this test closes the equivalent gap for
the release-artifact script, which had no coverage at all.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = PROJECT_ROOT / "scripts" / "generate_release_artifacts.py"
EXAMPLE_DESCRIPTOR = PROJECT_ROOT / "data" / "example_descriptor.json"


def _run_script(descriptor: Path, output_dir: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(SCRIPT_PATH),
            "--descriptor",
            str(descriptor),
            "--output-dir",
            str(output_dir),
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


class TestGenerateReleaseArtifacts:
    """The thin script validates the fixture descriptor and writes declared JSON."""

    def test_writes_declared_artifacts_for_the_shipped_fixture(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "reports"

        completed = _run_script(EXAMPLE_DESCRIPTOR, output_dir)

        assert completed.returncode == 0, completed.stderr
        report_path = output_dir / "descriptor_report.json"
        manifest_path = output_dir / "release_bundle_manifest.json"
        constraints_path = output_dir / "field_constraints.json"
        assert report_path.is_file()
        assert manifest_path.is_file()
        assert constraints_path.is_file()

        report = json.loads(report_path.read_text(encoding="utf-8"))
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        constraints = json.loads(constraints_path.read_text(encoding="utf-8"))

        assert report["valid"] is True
        assert report["field_count"] == 6
        assert report["file_count"] == 2
        assert report["findings"] == []
        assert manifest["valid"] is True
        assert manifest["release_boundary"] == "metadata-and-checksums-only"
        assert manifest["schema_fingerprint"] == report["schema_fingerprint"]
        assert constraints["schema_fingerprint"] == report["schema_fingerprint"]
        assert constraints["field_count"] == 6
        assert len(constraints["constraints"]) == 6

        summary = json.loads(completed.stdout)
        assert summary["valid"] is True
        assert set(summary["outputs"]) == {
            "descriptor_report.json",
            "release_bundle_manifest.json",
            "field_constraints.json",
        }

    def test_invalid_descriptor_is_still_reported_not_silently_passed(self, tmp_path: Path) -> None:
        broken = json.loads(EXAMPLE_DESCRIPTOR.read_text(encoding="utf-8"))
        broken.pop("license")
        descriptor_path = tmp_path / "broken_descriptor.json"
        descriptor_path.write_text(json.dumps(broken), encoding="utf-8")
        output_dir = tmp_path / "reports"

        completed = _run_script(descriptor_path, output_dir)

        assert completed.returncode == 0, completed.stderr
        report = json.loads((output_dir / "descriptor_report.json").read_text(encoding="utf-8"))
        summary = json.loads(completed.stdout)
        assert report["valid"] is False
        assert summary["valid"] is False
        assert any(finding["code"] == "missing_license" for finding in report["findings"])

    def test_missing_descriptor_fails_closed_without_partial_output(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "reports"

        completed = _run_script(tmp_path / "does_not_exist.json", output_dir)

        assert completed.returncode != 0
        assert "FileNotFoundError" in completed.stderr
        assert not output_dir.exists()
